global using Xamarin.Forms;
global using Xamarin.Forms.Xaml;
global using Shiny;
global using Prism;
global using Prism.Navigation;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;

global using reb.Resources;
global using reb.ShinyStartup;
global using reb.ShinyStartup.Modules;
global using reb.ViewModels;
global using reb.Views;
global using reb.Models;
global using reb.Settings.AppSettings;
