//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reb.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reb.Resources.Text.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string ErrorBody {
            get {
                return ResourceManager.GetString("ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string MotorList_Brand {
            get {
                return ResourceManager.GetString("MotorList_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No motor yet..
        /// </summary>
        internal static string MotorList_NoMotor {
            get {
                return ResourceManager.GetString("MotorList_NoMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notches number.
        /// </summary>
        internal static string MotorList_NotchesNumber {
            get {
                return ResourceManager.GetString("MotorList_NotchesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powers.
        /// </summary>
        internal static string MotorList_Powers {
            get {
                return ResourceManager.GetString("MotorList_Powers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in {0} motors..
        /// </summary>
        internal static string MotorList_Search {
            get {
                return ResourceManager.GetString("MotorList_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors.
        /// </summary>
        internal static string MotorList_Title {
            get {
                return ResourceManager.GetString("MotorList_Title", resourceCulture);
            }
        }
    }
}
